services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: shayan
      POSTGRES_USER: sun
      POSTGRES_PASSWORD: Alialiali1573
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge