create sequence public.gallery_items_seq start 109 increment 1;
create sequence public.showcase_items_seq start 4 increment 1;
create sequence public.provided_service_items_seq start 12 increment 1;

CREATE TABLE IF NOT EXISTS public.gallery_items (
    id int8 generated by default as identity,
    title VARCHAR(255) NOT NULL,
    item_description TEXT,
    image_byte BYTEA NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS public.showcase_items (
    id int8 generated by default as identity,
    title VARCHAR(30) NOT NULL,
    image_byte BYTEA NOT NULL,
    item_description VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS public.provided_service_items (
    id int8 generated by default as identity,
    title VARCHAR(255) NOT NULL,
    image_byte BYTEA NOT NULL,
    active BOOLEAN NOT NULL
);